name: Bug Report
description: バグ報告
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## バグ報告テンプレート
        発見したバグについて詳しく記入してください。

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: バグの深刻度に応じて選択
      options:
        - P0: Critical (本番障害・即時対応)
        - P1: High (本番影響あり・今週対応)
        - P2: Medium (開発に支障・今スプリント)
        - P3: Low (軽微・バックログ)
      default: 2
    validations:
      required: true

  - type: dropdown
    id: dod_level
    attributes:
      label: DoD Level (修正品質基準)
      description: 修正の品質レベル
      options:
        - Bronze (最小限の修正)
        - Silver (回帰テスト込み) ← 推奨
        - Gold (包括的テスト追加)
      default: 1
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: バグの説明
      description: 何が起きているか
      placeholder: 期待される動作と、実際の動作を説明してください
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: バグを再現する手順
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: 本来どう動作すべきか
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
      description: 現在どう動作しているか
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 環境
      description: 発生環境の情報
      value: |
        - ブラウザ:
        - OS:
        - 画面サイズ:
        - ログインユーザー種別:

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット（任意）
      description: 問題を示すスクリーンショットがあれば添付

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 修正完了条件
      description: 修正完了とみなす条件
      value: |
        - [ ] バグが修正されている
        - [ ] 再現手順で問題が発生しない
        - [ ] 回帰テストが追加されている

  - type: checkboxes
    id: checklist
    attributes:
      label: 事前確認
      options:
        - label: 重複Issueがないことを確認しました
          required: true
        - label: 再現手順を確認しました
          required: true
