name: "バグ報告"
description: "バグ・不具合の報告"
title: "[バグ]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## バグ報告テンプレート

        問題の再現・修正に必要な情報を詳しく記入してください。

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: このバグの深刻度は？
      options:
        - P0: 緊急（本番ダウン）
        - P1: 高（主要機能が壊れている）
        - P2: 中（機能が劣化している）
        - P3: 低（軽微な問題）
    validations:
      required: true

  - type: dropdown
    id: dod-level
    attributes:
      label: 品質レベル（DoD）
      description: 修正に必要な品質基準
      options:
        - Silver（カバレッジ85%・推奨）
        - Bronze（カバレッジ80%・応急処置）
        - Gold（カバレッジ95%・重要修正）
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: バグの説明
      description: どんなバグ？簡潔に説明してください
      placeholder: |
        何が起きた？
        何が起きるべきだった？
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: バグを再現するための詳細な手順
      placeholder: |
        1. ○○ページに移動
        2. △△ボタンをクリック
        3. □□までスクロール
        4. エラーが発生
    validations:
      required: true

  - type: input
    id: figma-link
    attributes:
      label: Figmaリンク（任意）
      description: |
        UIバグの場合、正しいデザインを示すFigmaへのリンク。
        UI/スタイリングの問題に便利。
      placeholder: "https://www.figma.com/file/..."

  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: 本来どうなるべき？
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット / エラーログ
      description: 該当する場合はスクリーンショットやエラーメッセージを追加
      placeholder: |
        スクリーンショットやエラーログをここに貼り付け。
        エラーメッセージ: ...

  - type: textarea
    id: environment
    attributes:
      label: 環境
      description: どこで発生した？
      placeholder: |
        - ブラウザ: Chrome 120
        - OS: macOS 14
        - URL: https://...
        - ユーザーロール: admin / reviewer

  - type: textarea
    id: affected-files
    attributes:
      label: 影響するファイル
      description: このバグを修正するために変更が必要そうなファイル
      placeholder: |
        - `src/components/...`
        - `src/app/api/...`
    validations:
      required: true

  - type: textarea
    id: test-plan
    attributes:
      label: テスト計画
      description: 修正をどう検証する？
      placeholder: |
        - [ ] ユニットテスト追加
        - [ ] E2Eテスト追加
        - [ ] 手動検証手順
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 受け入れ条件
      description: このバグがいつ修正完了と言える？
      placeholder: |
        - [ ] バグが再現しなくなった
        - [ ] テストが通る
        - [ ] 既存機能に影響なし
    validations:
      required: true
