name: "Bug Report"
description: "Report a bug or issue"
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template
        Please provide detailed information to help us reproduce and fix the issue.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How severe is this bug?
      options:
        - P0: Critical (Production down)
        - P1: High (Major feature broken)
        - P2: Medium (Feature degraded)
        - P3: Low (Minor issue)
    validations:
      required: true

  - type: dropdown
    id: dod-level
    attributes:
      label: DoD Level
      description: Required quality level for the fix
      options:
        - Silver (85% coverage - Recommended)
        - Bronze (80% coverage - Quick fix)
        - Gold (95% coverage - Critical fix)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of what the bug is
      placeholder: |
        What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: figma-link
    attributes:
      label: Figma Link (Optional)
      description: |
        If this is a UI bug, link to Figma showing the correct design.
        Useful for UI/styling issues.
      placeholder: "https://www.figma.com/file/..."

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Error Logs
      description: Add screenshots or error messages if applicable
      placeholder: |
        Paste screenshots or error logs here.
        Error message: ...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Where did this happen?
      placeholder: |
        - Browser: Chrome 120
        - OS: macOS 14
        - URL: https://...
        - User role: admin / reviewer

  - type: textarea
    id: affected-files
    attributes:
      label: Affected Files
      description: Files that likely need to be changed to fix this bug
      placeholder: |
        - `src/components/...`
        - `src/app/api/...`
    validations:
      required: true

  - type: textarea
    id: test-plan
    attributes:
      label: Test Plan
      description: How to verify the fix?
      placeholder: |
        - [ ] Unit test added
        - [ ] E2E test added
        - [ ] Manual verification steps
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: When is this bug considered fixed?
      placeholder: |
        - [ ] Bug no longer reproducible
        - [ ] Tests pass
        - [ ] No regression
    validations:
      required: true
