name: Feature Request
description: 機能要望・新機能追加
title: "[Feature]: "
labels: ["feature", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 機能要望テンプレート
        新機能の要望を記入してください。

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: 優先度を選択してください
      options:
        - P0: Critical (本番障害相当)
        - P1: High (今週対応)
        - P2: Medium (今スプリント)
        - P3: Low (バックログ)
      default: 2
    validations:
      required: true

  - type: dropdown
    id: dod_level
    attributes:
      label: DoD Level (品質基準)
      description: 求める品質レベルを選択
      options:
        - Bronze (プロトタイプ・80%カバレッジ)
        - Silver (開発版・85%カバレッジ) ← 推奨
        - Gold (本番品質・95%カバレッジ)
      default: 1
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 機能説明
      description: 追加したい機能の説明
      placeholder: どのような機能を追加したいですか？
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 背景・動機
      description: なぜこの機能が必要ですか？
      placeholder: この機能が解決する課題や、もたらすメリットを説明してください

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ条件
      description: 完了とみなす条件をチェックリストで記入
      value: |
        - [ ]
        - [ ]
        - [ ] E2Eテストが追加されている
    validations:
      required: true

  - type: textarea
    id: technical_notes
    attributes:
      label: 技術的な補足（任意）
      description: 実装に関するヒントや制約など
      placeholder: 関連ファイル、使用技術、制約事項など

  - type: checkboxes
    id: checklist
    attributes:
      label: 事前確認
      options:
        - label: 重複Issueがないことを確認しました
          required: true
        - label: CLAUDE.mdの開発ルールを確認しました
          required: true
