name: "Feature Request"
description: "Propose a new feature with Figma mockup"
title: "[Feature]: "
labels: ["feature", "needs-triage", "design-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request Template
        Please fill out the sections below to help us understand your feature request.

        ### ⚠️ Figma-First ルール
        **UI/UX変更を含む機能は、Figmaモックアップを先に作成してからこのIssueを作成してください。**
        Figmaリンクがない場合、`design-review` ラベルが付与され、実装は開始されません。

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this feature?
      options:
        - P1: High (This sprint)
        - P2: Medium (Next sprint)
        - P3: Low (Backlog)
    validations:
      required: true

  - type: dropdown
    id: dod-level
    attributes:
      label: DoD Level
      description: Required quality level for this feature
      options:
        - Silver (85% coverage - Recommended)
        - Bronze (80% coverage - Prototype)
        - Gold (95% coverage - Production)
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Background
      description: Why is this feature needed? What problem does it solve?
      placeholder: |
        - Current situation: ...
        - Problem: ...
        - Expected benefit: ...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature in detail
      placeholder: |
        As a [user type], I want to [action] so that [benefit].
    validations:
      required: true

  - type: input
    id: figma-link
    attributes:
      label: Figma Mockup Link
      description: |
        **UI機能は必須** - Issue作成前にFigmaを作成してリンクを貼ってください。
        リンクがない場合、実装は開始されません（design-reviewで保留）。
        バックエンドのみの機能はスキップ可。
      placeholder: "https://www.figma.com/file/..."
    validations:
      required: false

  - type: input
    id: v0-link
    attributes:
      label: v0 Generation Link (Optional)
      description: |
        v0.devでUIを生成した場合、そのURLを貼ってください。
        実装時にコードを流用できます。shadcn/ui + Tailwindなのでそのまま使えます。
      placeholder: "https://v0.dev/chat/..."
    validations:
      required: false

  - type: checkboxes
    id: figma-checklist
    attributes:
      label: Design Checklist
      description: Confirm the following for UI/UX features
      options:
        - label: "Figma mockup created and linked above"
        - label: "Mobile responsive design considered"
        - label: "Dark mode colors verified"
        - label: "Accessibility (contrast, font size) checked"
        - label: "This is a backend-only feature (no UI changes)"

  - type: checkboxes
    id: variant-checklist
    attributes:
      label: Component Variant Checklist（UIコンポーネントのバリアント）
      description: |
        本番品質のUIには全状態パターンのデザインが必要です。
        該当するバリアントをv0/Figmaで作成し、リンクに含めてください。
        バックエンドのみの機能はスキップ可。
      options:
        - label: "⚫ **Default** - 正常データ表示状態"
        - label: "⚫ **Loading** - データ読み込み中（スケルトンUI/スピナー）"
        - label: "⚫ **Empty** - データなし状態（「データがありません」等）"
        - label: "⚫ **Error** - エラー発生時（再試行ボタン付き）"
        - label: "◯ **Disabled** - 無効状態（操作不可）"
        - label: "◯ **Success/Warning/Danger** - データパターン別の色分け表示"
        - label: "△ **Size variants** - サイズ違い（sm/md/lg）"
        - label: "△ **Hover/Focus/Active** - インタラクション状態"
        - label: "該当なし（バックエンドのみ/状態変化のないUI）"

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List specific requirements as checkboxes
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Requirement 3
    validations:
      required: true

  - type: textarea
    id: test-plan
    attributes:
      label: Test Plan
      description: How should this feature be tested?
      placeholder: |
        - Unit tests: ...
        - E2E tests: ...
        - Manual verification: ...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: When is this feature considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] All tests pass
    validations:
      required: true

  - type: textarea
    id: affected-files
    attributes:
      label: Affected Files (Optional)
      description: List files that will likely need changes
      placeholder: |
        - `src/components/...`
        - `src/app/...`
